baseurl = "/"
languageCode = "en-us"
title = "Tasty Licks"

[params]
  description = "An example website for restaurants built by [@eliwilliamson](https://github.com/eliwilliamson) using [Victor Hugo](https://github.com/netlify/victor-hugo)."

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 2

[[menu.main]]
    name = "Drinks"
    url  = "/drinks"
    weight = 3

[[menu.main]]
    name = "Business Consulting"
    url  = "/biz"
    weight = 4

[[menu.main]]
    name = "Technology Consulting"
    url  = "/tech"
    weight = 5

[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 6
