backend:
  name: git-gateway

media_folder: "src/img/gallery" # Folder where user uploaded files should go

collections:
  - name: food
    label: "Food Item" # Used in the UI, ie.: "New Post"
    folder: "site/content/food" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
      - {label: "Price", name: "price", widget: "string"}
  - name: drinks
    label: "Drink Item" # Used in the UI, ie.: "New Post"
    folder: "site/content/drinks" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Drink", name: "title", widget: "string"}
      - {label: "Drink Marker", name: "categories", widget: "hidden", default: ["drinks"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Drink", name: "type", widget: "string", default: "beer"}
      - {label: "Price", name: "price", widget: "string"}
  - name: analytics
    label: "Data Analytics"
    folder: "site/content/analytics" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Analysis Item", name: "title", widget: "string"}
      - {label: "Analysis Type", name: "categories", widget: "list", default: ["visualization", "predictive", "prescriptive", "accounting"]}
  - name: technology
    label: "Technology Consulting"
    folder: "site/content/tech" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Technology Item", name: "title", widget: "string"}
      - {label: "Technology Type", name: "categories", widget: "list", default: ["IaaS", "PaaS", "automation", "CICD"]}
  - name: gallery
    label: "Gallery Image" # Used in the UI, ie.: "New Post"
    folder: "site/content/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Gallery Image", name: "image", widget: "image"}
